[pytest]
pythonpath = .

markers =
    smoke: Tests that validate critical system functionality
    regression: Tests that validate complete functionality and business rules
    e2e: End-to-End tests that simulate complete user journeys
    login: Tests related to login functionality
    cart: Tests related to shopping cart functionality
    checkout: Tests related to checkout functionality
    purchase: Tests related to purchase process
    
testpaths = tests/specs
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = --strict-markers -v